### ISSUE TITLE
Comparison with Kanel

### ISSUE THREAD

**Issue by tamlyn** [aldis-ameriks/pg-typegen#41]
Are you aware of https://github.com/kristiandupont/kanel? 

The scope and features of both projects seem very similar. Perhaps you could learn from each other's approach, or even combine efforts.

**Comment by aldis-ameriks** [comment]
Hi @tamlyn,
Thanks for the input.

The motivation behind pg-typegen was to create an opinionated, zero configuration, simple and easy to use type generator while also keeping the dependency tree as light as possible.
Looks like kanel has wider set of features, but also the dependency tree is much larger.
