### ISSUE TITLE
An identifier or keyword cannot immediately follow a numeric literal

### ISSUE THREAD

**Issue by fibonaci** [aldis-ameriks/pg-typegen#49]
https://github.com/aldis-ameriks/pg-typegen/blob/d483415ece09540d024c39a13bc74ce075c5c090/src/typescript.js#L36
Can we update `formatEnumName` function with extra check of leading char to allow pg types start with number? 

`function formatEnumName(opts, name) {
  if (opts.pascalEnums && !/^[0-9]*$/.test(name.charAt(0))) {
    return toPascalCase(name);
  }

  return formatName(name);
}`

**Comment by aldis-ameriks** [comment]
Should be fixed within v3.7.1.
